title: PYT101 - Introduction to programming with Python
author: Charles Coulombe
copyright: '2024'
logo: ""
only_build_toc_files: true

# https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'force'
  allow_errors: true

# Information about where the book exists on the web
repository:
  url: https://github.com/ccoulombe/cq-intro-python.git
  branch: main
  path_to_book: "./_book"

# https://jupyterbook.org/structure/configure.html#exclude-pages-from-your-build
exclude_patterns:
  - README.md

# https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  # favicon: images/logo.png
  use_repository_button: true
  use_issues_button: true

launch_buttons:
  binderhub_url: ""

sphinx:
  config:
    language: en
